import Head from 'next/head'
import styles from '../styles/Home.module.css'
import AllData from '../public/Archive/general.json'
import { ImagesComp} from "./components/Image";
import {Tools} from "./components/Tools";
import {useState} from "react";

function Home() {

    const [visibleMeta, setVisibleMeta] = useState(false)
    const [item, setItem] = useState(0)
    const [allKey, setKey] = useState(Object.keys(AllData))

    return (
        <div className={styles.container}>
            <Head>
                <title>Создано на NextJS</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Просмост фотонарушение
                </h1>
                <div className={styles.grid}>
                    <ImagesComp item={AllData[allKey[item]]} visibleMeta={visibleMeta}/>
                </div>
                <div>{item + 1} из {allKey.length}</div>
                <div className={styles.grid}>
                    <Tools
                        count={allKey.length}
                        item={item} setItem={setItem}
                        setVisibleMeta={setVisibleMeta} visibleMeta={visibleMeta}/>
                </div>
            </main>
            <footer className={styles.footer}>
                Тут могла быть ваша реклама
            </footer>
        </div>
    )
}

export default Home
